### ISSUE TITLE
Positioning of glyphs on macOS is wrong

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1270] opened 2017-05-18 17:56 UTC
I showed this to @kvark in real life.

**Comment by jrmuizel** [comment] 2017-06-16 18:25
It looks like this happens on Windows as well.

**Comment by glennw** [comment] 2017-09-04 22:46
@jrmuizel  Can we get some more information on this? It's not actionable as is...

**Comment by mstange** [comment] 2017-09-07 17:12
This is mostly fixed, except in some rare cases letters are rendered one device pixel too far to the left. For example, open this testcase in Firefox with Webrender + webrendest:

```
data:text/html,<div style="background:white;padding:5px;">This is some text. And some more text. And some more.</div><style>div:hover { filter: blur(0px); }</style>
```

```html
<div style="background:white;padding:5px;">
  This is some text. And some more text. And some more.
</div>
<style>
div:hover {
  filter: blur(0px);
}
</style>
```

This testcase applies a no-op filter on hover, which makes current Firefox+webrender builds fall back to Gecko rendering for the affected text. So you can easily see differences in text rendering between webrender and Gecko / Skia just by moving your mouse. (In the past this was possible using text selection, but now that we support text selection with webrender, we have to be smarter...)

On Mac on a HiDPI display, I see the following letters move one screen pixel to the right on hover:
```
This is some text. And some more text. And some more.
                          ^        ^^   ^^ ^       ^
```
Or, in other words, webrender drew these letters one pixel too far to the left.

However, the glyph instance that webrender chose was the correct one; all the anti-aliasing on the glyphs looks the same. (If you ignore the fact that it also switches between subpixel AA and not subpixel AA. I think we explicitly disable subpixel AA inside filters.)

**Comment by kvark** [comment] 2017-09-07 17:16
> In the past this was possible using text selection, but now that we support text selection with webrender, we have to be smarter...

😆 

>Or, in other words, webrender drew these letters one pixel too far to the left.

So, pixel snapping strikes back?

**Comment by Gankro** [comment] 2017-09-14 17:11
This is probably the last major text bug in gecko+webrender.

(note: markus' test-case is useful for seeing the issue, but we currently have a wontfix bug that disables subpixel-aa in the native gecko renderer if webrender is enabled at all, so just keep in mind that the aa values may change a bit too)

**Comment by glennw** [comment] 2017-09-15 03:31
I'm still working on getting a FF build on my mac (don't ask), but I've done some testing of this on a Linux build in the meantime.

If I disable subpx AA in WR on Linux, then the test case above looks *exactly* the same whether hovering or not.

This suggests that the issue is probably not related to snapping (since that's platform independent), and instead is an issue in the mac platform font implementation. Once I get a mac build, I'll be able to confirm if this is the case. If it's an issue in the mac font rasterization code, the fix should be relatively trivial.

**Comment by glennw** [comment] 2017-09-15 07:11
Although, now that I have finally reproduced it on mac, it does very much look like a snapping issue. Interesting!

**Comment by glennw** [comment] 2017-09-15 09:17
Ohh! I can see at least one problem.

When rendering with sub-pixel positioning, we truncate the fractional part of the position in the vertex shader, since it's accounted for during rasterization. *But* I don't think this is done correctly.

For example, we quantize the sub-pixel position to 0.25 accuracy, but we then truncate the entire fractional part in the vertex shader. We need to be a bit smarter here and only subtract the quantized amount. I'm not sure if this completely fix the issue, but it's definitely wrong - I'll fix that and hopefully it might fix the problem completely :)

**Closed** 2017-09-19 01:02 UTC
