### ISSUE TITLE
Support running wrench with ANGLE on Windows.

### ISSUE THREAD

**Issue by nical** [servo/webrender#2006] opened 2017-11-07 16:38 UTC
It should prove handy whenever we'll get to debugging ANGLE/D3D specific bugs, and D3D11 tends to have much better tooling available than GL, for example pixel history and debugging in renderdoc.

**Comment by kvark** [comment] 2017-11-07 21:09
Pretty sure this is already done. Wrench uses `glutin` for initialization, and that one checks for libEGL as of https://github.com/servo/glutin/pull/112 . All you need is to drop Angle's `libEGL.dll` in the folder with wrench executable.

**Comment by glennw** [comment] 2017-11-08 06:13
This is a duplicate of #1432.

**Closed by glennw** 2017-11-08 06:13 UTC
Labels: area: infrastructure
