### ISSUE TITLE
reddit.com/r/overwatch has 250-300 of draw calls

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2219] opened 2017-12-12 22:18 UTC
See https://bugzilla.mozilla.org/show_bug.cgi?id=1424924

http://jrmuizel.github.io/webrender/reddit-overwatch.zip

**Comment by glennw** [comment] 2017-12-12 22:49
Looks like a huge number of batch breaks caused by overlapping borders vs. text runs. I don't see any large # of border primitives though, so this might be a bug with zero alpha border edges or something like that?

**Comment by glennw** [comment] 2018-03-16 06:32
Checked today and this is still causing a huge number of draw calls. Needs more investigation.

**Comment by glennw** [comment] 2018-04-06 03:53
This is a bit better now - ~150 - 200 draw calls. However, GPU time is not good at all, ~15ms for what appears visually as a simple site. Needs more investigation.

**Comment by gw3583** [comment] 2018-06-18 05:03
On the new reddit design, this now has ~40-50 draw calls and runs very well.

On the old reddit design, there is ~100-140 draw calls. This is an improvement but is still running slower than ideal. There are a large number of color and alpha targets being allocated. The color targets should be fixed as we cache more effect targets. The alpha targets may indicate a bug in additional clip mask allocation, as there doesn't appear to be a visual need for all these clips.

There are a large number of mix-blend and blend filters being applied when they don't need to be - we should detect this case and handle it as a normal image brush.

The changes above should make the old design run much better.

**Comment by kvark** [comment] 2018-06-19 19:06
Good info, @gw3583 ! I'd be curious to see what kind of mix-blend/blend filter combinations they use that we could simplify.

**Comment by gw3583** [comment] 2019-02-04 22:32
Both the new and old design seem to have ~50-60 draw calls and run smoothly for me now.

**Closed by gw3583** 2019-02-04 22:32 UTC
Labels: area: performance, bugzilled
