### ISSUE TITLE
3d transforms problem on https://youriguide.com/sample-full/

### ISSUE THREAD

**Issue by Darkspirit** [servo/webrender#3094] opened 2018-09-20 15:52 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1492859 ([Screencast](https://bugzilla.mozilla.org/attachment.cgi?id=9010649))

(I am unsure whether it's fixed in the try build from https://github.com/servo/webrender/pull/3093#issue-216981742 or not. This bug might be fixed, but in general it looks as bad as it wouldn't include the Nvidia fix from #3073.)

**Comment by kvark** [comment] 2018-09-20 17:54
Thank you for filing the issue! Not fixed by #3093, assigning to myself

**Comment by Darkspirit** [comment] 2018-09-21 19:17
The problem from the [screencast](https://bugzilla.mozilla.org/attachment.cgi?id=9010649) seems to be fixed by [bug 1489337](https://bugzilla.mozilla.org/show_bug.cgi?id=1489337)?

Let's turn around a bit further.

![screenshot_20180921_211153](https://user-images.githubusercontent.com/17962859/45901519-77cdc500-bde3-11e8-948c-0b56a9f68df5.png)

**Comment by kvark** [comment] 2018-10-23 01:41
I looked at this remaining visual issue with the corners, and it appears that WR gets invalid image templates.
Here is one for the view angle that shows the issue:
```ron
            ((64), 2101): (
                data: "externals/7",
                descriptor: (
                    format: BGRA8,
                    size: (1, 1),
                    stride: Some(4),
                    offset: 0,
                    is_opaque: true,
                    allow_mipmaps: false,
                ),
                tiling: None,
            ),
```
Here is one where the issue is not shown:
```ron
            ((64), 2440): (
                data: "externals/155",
                descriptor: (
                    format: BGRA8,
                    size: (1024, 1024),
                    stride: Some(4096),
                    offset: 0,
                    is_opaque: true,
                    allow_mipmaps: false,
                ),
                tiling: None,
            ),
```

Hence, it doesn't appear to be WR issue (any more). Calling @aosmond for the last piece of input before we close this side of the issue (and leave Gecko side open).

**Comment by gw3583** [comment] 2019-02-04 22:40
Marked fixed in bugzilla.

**Closed by gw3583** 2019-02-04 22:40 UTC
Labels: bugzilled, priority: soon, type: bug
