### ISSUE TITLE
Regression in the rendering of rounded borders

### ISSUE THREAD

**Issue by Zirro** [servo/webrender#2754] opened 2018-05-11 17:44 UTC
There seems to have been a recent regression in the way rounded borders are rendered. Here is a [test case](https://rawgit.com/Zirro/c72becdcd5c05eb6547ad2cc9e5638aa/raw/dc6439f1d86c12430bc15c64afc914a68b32cc14/rounded-border.html), with screenshots below.

Without WebRender:

<img width="952" alt="Without WebRender" src="https://user-images.githubusercontent.com/3169418/39937613-95380aca-5550-11e8-8834-3caf773a4bd3.png">

With WebRender:

<img width="952" alt="With WebRender" src="https://user-images.githubusercontent.com/3169418/39937631-a4c33230-5550-11e8-8524-cc9d945cef4d.png">

This seems to have changed within the last month, as the circle can be seen rendering properly in [this issue](https://github.com/servo/webrender/issues/2590) created at the end of March.

**Comment by Zirro** [comment] 2018-05-15 17:37
@Darkspirit This could be the case, as the flickering boxes (which now appear if I make the window small enough to scroll) seem to align with some of the missing parts of the border.

That said, something must still have changed as I used to see the dots in the circle on https://rawgit.com/Zirro/03f0e2d19b087db29b1f069e014e3ee5/raw/0f32535d70e56185e01e4f9be860afc4dc4fec79/fireworks.html when I created that issue, and for some time afterwards.

I will have another look at this test case when #2590 has been resolved, to see if they are indeed the same issue or two separate ones.

**Comment by mrobinson** [comment] 2018-05-25 07:54
Hrm. I'm having trouble reproducing this one as well. I do see artifacts in https://rawgit.com/Zirro/03f0e2d19b087db29b1f069e014e3ee5/raw/0f32535d70e56185e01e4f9be860afc4dc4fec79/fireworks.html, though they don't seem to be related to to dot or dash rendering.

**Comment by Zirro** [comment] 2018-05-27 16:40
If it can help to narrow down the specific rendering issues I'm seeing by looking at certain hardware/drivers, I'm on a MacBook Pro (Early 2013) with Intel HD Graphics 4000 and a NVIDIA GeForce GT 650M with High Sierra.

**Comment by kvark** [comment] 2018-05-30 12:59
Works fine on my end (Linux/Intel) with or without resizing.

**Comment by MartinRogalla** [comment] 2018-06-07 15:47
Seeing the same issue on MacBookPro12,1 (Retina, 13-inch, Early 2015) w/ Intel Iris Graphics 6100.

![screen shot 2018-06-07 at 17 46 50](https://user-images.githubusercontent.com/1066157/41110895-cbc84368-6a7a-11e8-91f9-238d12f94746.png)

**Comment by Zirro** [comment] 2018-06-12 13:10
This appears to have been resolved - quite likely through the merging of https://github.com/servo/webrender/pull/2795. This is what I see now:

<img width="952" alt="Screenshot" src="https://user-images.githubusercontent.com/3169418/41291407-df868daa-6e4f-11e8-8f91-46a286da38ab.png">

The border placement could use some improvements to match the non-WebRender version, but I think this issue can be closed at this point.

Latest WebRender has not been merged into Servo yet, but is available in Firefox Nightly.
@MartinRogalla Could you verify whether this is fixed in latest Nightly for you?

**Comment by Darkspirit** [comment] 2018-06-12 14:34
[Fixed for me too.](https://bugzilla.mozilla.org/show_bug.cgi?id=1461513#c5)

**Comment by MartinRogalla** [comment] 2018-06-12 16:33
Looks a bit better, but I see some strange behaviour on Nightly. The elements change if I click on them. I'm not sure if this is related. Please see the attached GIF:
![out](https://user-images.githubusercontent.com/1066157/41303762-7b0c604c-6e6e-11e8-8aa9-8ede9ee573d2.gif)

Please let me know if you want me to provide any additional information.

**Comment by Zirro** [comment] 2018-06-12 16:44
That is strange behaviour indeed. For what it's worth, I can't seem to reproduce it on my machine.

**Comment by gw3583** [comment] 2018-06-18 03:48
It seems like the original bug has been fixed. We should probably close this bug and open a new one with the behavior mentioned above by @MartinRogalla - I'm also unable to reproduce that issue on any of my local test machines - it may be a driver specific issue.

**Closed** 2018-07-04 17:44 UTC
Labels: bugzilled, type: bug
