### ISSUE TITLE
AMD/Linux register error when compiling shaders

### ISSUE THREAD

**Issue by eyelash** [servo/webrender#1601] opened 2017-08-23 10:26 UTC
When running `cargo run --example basic` I get the following output:
```
OpenGL version 3.3 (Core Profile) Mesa 17.1.6
Shader resource path: None
EE r600_shader.c:3661 r600_shader_from_tgsi - GPR limit exceeded - shader requires 305 registers
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=0) -12
EE r600_shader.c:3661 r600_shader_from_tgsi - GPR limit exceeded - shader requires 243 registers
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=0) -12
EE r600_shader.c:3661 r600_shader_from_tgsi - GPR limit exceeded - shader requires 305 registers
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=0) -12
EE r600_shader.c:3661 r600_shader_from_tgsi - GPR limit exceeded - shader requires 243 registers
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:800 r600_shader_select - Failed to build shader variant (type=0) -12
```
My graphics card is a Radeon HD 2400 XT running the latest Mesa drivers on Linux.
I get the same error messages when running the servo nightly build and webpages do not render correctly. I know this card is probably too old to properly run webrender but I'm reporting this bug anyway in the hope that there might be some solution to at least render webpages correctly in servo.
If want me to provide more information or try some patches I will happily do so.

**Comment by nical** [comment] 2017-08-23 11:42
Added to the [list of driver issues](https://github.com/servo/webrender/wiki/Driver-issues#1601---gpr-limit-exceeded-shader-requiring-too-many-registers). Hopefully the work with splitting shader shared preludes will help, although it would make sense that this issue is happening after the compiler eliminated the dead code.

**Comment by asppsa** [comment] 2017-11-15 05:18
FWIW I am seeing more or less the same thing with a Radeon HD 5750 (Juniper PRO) and slightly more recent Mesa:

~~~ bash
$ cargo run --example basic
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/asp/src/webrender/target/debug/examples/basic`
OpenGL version 3.3 (Core Profile) Mesa 17.2.5
Shader resource path: None
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:787 r600_shader_select - Failed to build shader variant (type=0) -1
EE r600_shader.c:3663 r600_shader_from_tgsi - GPR limit exceeded - shader requires 244 registers
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:787 r600_shader_select - Failed to build shader variant (type=0) -12
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:787 r600_shader_select - Failed to build shader variant (type=0) -1
EE r600_shader.c:3663 r600_shader_from_tgsi - GPR limit exceeded - shader requires 244 registers
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:787 r600_shader_select - Failed to build shader variant (type=0) -12
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:787 r600_shader_select - Failed to build shader variant (type=0) -1
EE r600_shader.c:3663 r600_shader_from_tgsi - GPR limit exceeded - shader requires 244 registers
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
EE r600_state_common.c:787 r600_shader_select - Failed to build shader variant (type=0) -12
EE r600_shader.c:183 r600_pipe_shader_create - translation from TGSI failed !
[ ... repeats an infinitum ... ]
~~~

I see the exact same errors if I try run Firefox Nightly [with WebRender enabled][1].  In the `cargo run` case, any interaction, - such as clicking or moving the mouse in the window - is enough to generate more repetitions of the errors.  In Firefox, there is just a constant stream of the errors.

[1]: https://mozillagfx.wordpress.com/2017/11/06/webrender-newsletter-9/

**Comment by eyelash** [comment] 2017-11-15 09:49
Might be [this bug](https://bugs.freedesktop.org/show_bug.cgi?id=99349) which was recently fixed (the fix will be in Mesa 17.3).

**Comment by asppsa** [comment] 2017-11-16 03:37
@eyelash, compiling & running mesa from git seems to have gotten rid of the messages for me!  Will try again when there's a 17.3 release

**Comment by glennw** [comment] 2017-11-16 04:08
Thanks for testing that!

**Comment by ncweeaver** [comment] 2017-12-03 15:15
I was as well impacted by this bug with an AMD RV710, such as in: https://bugzilla.mozilla.org/show_bug.cgi?id=1407254 Here's the logs when debugging https://gist.githubusercontent.com/anonymous/d7c4634bd02790cd32b30fec8e1b3822/raw/6b632bfdef81e80a8a60239d7868947bce8d4d96/debug.txt

I can confirm that when using the latest drivers from https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers this issue disappears.

**Comment by glennw** [comment] 2017-12-03 20:00
Closing, since this is a driver bug with a known update fix.

**Closed by glennw** 2017-12-03 20:00 UTC
Labels: type: bug
