### ISSUE TITLE
Bad looking box-shadow 

### ISSUE THREAD

**Issue by kasper93** [servo/webrender#2625] opened 2018-04-06 00:27 UTC
Hi,

I noticed that _top sites_ on `about:newtab` page have bad looking box border/shadow.  Rounded corners look bad, but also straight lines are blurred and if you look closely top line is thinner than bottom line. Screenshot taken from Firefox build 20180405153002 with dark theme selected.

webrender enabled:
![image](https://user-images.githubusercontent.com/1126053/38397722-8be13fb4-393f-11e8-91b8-e0eefa288b0d.png)

webrender disabled:
![image](https://user-images.githubusercontent.com/1126053/38397772-d9505244-393f-11e8-82fd-ae62cdd5a11c.png)

Regards,
Kacper

**Comment by DivineGod** [comment] 2018-04-07 07:30
I've noticed some that might be similar (I can't really tell from the screenshots) and filed https://bugzilla.mozilla.org/show_bug.cgi?id=1452351

**Comment by Darkspirit** [comment] 2018-04-07 13:12
* [ ] [bug 1451478](https://bugzilla.mozilla.org/show_bug.cgi?id=1451478) | Broken slider buttons on [ticketmaster.com](https://www1.ticketmaster.com/angels-in-america-ny-parts-1-new-york-new-york-04-14-2018/event/0300533BA0893984?artistid=2419828) at different zoom levels 
* [ ] [bug 1452289](https://bugzilla.mozilla.org/show_bug.cgi?id=1452289) | Broken box-shadow on [mozilla.org](https://www.mozilla.org/en-US/firefox/)
* [ ] [bug 1452351](https://bugzilla.mozilla.org/show_bug.cgi?id=1452351) | box shadow rendering issue on [imdb.com](https://www.imdb.com/) ([testcase1](https://bugzilla.mozilla.org/attachment.cgi?id=8965931) | "the only point it triggers is in full page mode": [testcase2](https://s.codepen.io/DivineGod/fullpage/geQLqa))

**Comment by pcwalton** [comment] 2018-09-17 20:33
I can't reproduce, so I believe this was fixed. Closing. Please feel free to reopen if you still see this issue!

**Closed by pcwalton** 2018-09-17 20:33 UTC
Labels: bugzilled, type: bug
