### ISSUE TITLE
Add a capability to remove pipeline related data from Scene

### ISSUE THREAD

**Issue by sotaroikeda** [servo/webrender#930] opened 2017-02-27 01:24 UTC
When a specific pipeline is deleted, the pipeline related data needs to be removed from Scene. But it seems not implemented. Is it correct?

**Comment by jrmuizel** [comment] 2017-02-27 02:21
See also https://github.com/servo/webrender/issues/691

**Comment by kvark** [comment] 2017-05-26 17:45
Dupe of #691

**Closed by kvark** 2017-05-26 17:45 UTC
