### ISSUE TITLE
MotionMark CSS bouncing circles doesn't run fast enough

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2045] opened 2017-11-15 21:16 UTC
http://browserbench.org/MotionMark/developer.html?test-interval=30&display=minimal&tiles=big&controller=ramp&frame-rate=50&kalman-process-error=1&kalman-measurement-error=4&time-measurement=performance&suite-name=HTMLsuite&test-name=CSSbouncingcircles&complexity=143

I'm not exactly sure where the problem is but I it looks like webrender might be spending a lot of CPU time.

**Comment by glennw** [comment] 2017-11-15 21:26
Note to self: @jrmuizel thinks this might be Gecko-related, so don't need to look into this just yet.

**Comment by jrmuizel** [comment] 2017-11-15 21:27
Turns out I'm wrong. This is still Gecko bound. Style (something weird is happening according to @emilio) and DisplayList building (we have a bunch of debug code on nightly that's trying to catch a crash)

**Comment by glennw** [comment] 2017-11-15 21:42
FWIW many of the MM tests are also style-bound in Servo too.

**Comment by emilio** [comment] 2017-11-16 04:29
My profile looks wildly different from what @mstange showed to me:

  https://perf-html.io/public/d8b8f4bfd0cf029444a0a43e44d68d89e1f9065f/calltree/?hiddenThreads=&thread=4&threadOrder=0-2-3-4-1&v=2

Unless there's something osx-specific (maybe in the UA sheets in Gecko) that would cause that (there was a bunch of time on style invalidation code), I don't know what to make of that profile, style looks fast there... we could try to optimize allocations during `ProcessPostTraversal`, but...

**Comment by emilio** [comment] 2017-11-16 04:30
> FWIW many of the MM tests are also style-bound in Servo too.

Yeah, but this is because of a largely different reason IIUC, which is the style serialization code running for every style attribute setter, something we cannot really fix easily until we get rid of the old style system in Gecko unfortunately :(

**Comment by emilio** [comment] 2017-11-16 04:32
(For reference, the URL I was using to get more circles and such is http://browserbench.org/MotionMark/developer.html?test-interval=30&display=minimal&tiles=big&controller=fixed&frame-rate=50&kalman-process-error=1&kalman-measurement-error=4&time-measurement=performance&suite-name=HTMLsuite&test-name=CSSbouncingcircles&complexity=500)

**Comment by emilio** [comment] 2017-11-16 05:02
(That being said, it seems I'm painting in software, so maybe it's just an effect of the painting getting much slower. I'll try to take more numbers tomorrow profiling the style threads)

**Comment by glennw** [comment] 2017-11-22 06:58
I confirmed with current Gecko that this doesn't appear to be WR-limited, and gets a better score than with WR disabled. Closing for now, but please re-open if there is WR related work to do here.

**Closed by glennw** 2017-11-22 06:58 UTC
Labels: area: performance
