### ISSUE TITLE
some text-shadows don't show up

### ISSUE THREAD

**Issue by Gankro** [servo/webrender#2508] opened 2018-03-12 19:52 UTC
Seems this has been happening for a month, and I don't see any consistent pattern.

The following reftest doesn't render the red shadow. Removing the black shadow makes the red one show up.

```
--- # A simple example of two shadows
root:
  items:
        -
          type: "shadow"
          bounds: [14, 18, 205, 35]
          blur-radius: 2
          offset: [-2, -2]
          color: [255, 0, 0, 1]
        -
          type: "shadow"
          bounds: [14, 18, 205, 35]
          blur-radius: 2
          offset: [2, 2]
          color: [0, 0, 0, 1]
        -
          bounds: [14, 18, 205, 35]
          glyphs: [55, 75, 76, 86, 3, 76, 86, 3, 87, 75, 72, 3, 69, 72, 86, 87]
          offsets: [16, 43, 35.533333, 43, 51.533333, 43, 60.4, 43, 72.833336, 43, 80.833336, 43, 89.7, 43, 102.13333, 43, 110.13333, 43, 119, 43, 135, 43, 149.2, 43, 157.2, 43, 173.2, 43, 187.4, 43, 196.26666, 43]
          size: 18
          color: [0, 0, 0, 1]
          font: "VeraBd.ttf"
        -
          type: "pop-all-shadows"
```

The test that should notice this, shadow-many, is only !='d so this slipped through. Also sometimes shadows do show up, so some other tests pass fine??

[Bugzilled](https://bugzilla.mozilla.org/show_bug.cgi?id=1444985)

**Comment by Gankro** [comment] 2018-03-12 20:01
To be clear, it's not just "oh the last shadow wins", https://gankro.github.io/blah/webtests/text.html has a ton of "only one shadow" elements that are missing any shadows.

**Comment by glennw** [comment] 2018-03-13 21:28
(from IRC):

The problem is that https://github.com/servo/webrender/blob/2c6aa7365e4a1435ff98ab6b15e966306681d7d6/webrender/src/batch.rs#L376 does not do what I was expecting. When the keys are the same, the values don't get merged together. So we need to make this hash map merge a bit smarter here.

**Closed** 2018-03-14 06:40 UTC
Labels: bugzilled, type: bug
