### ISSUE TITLE
Opacity group compositing treats premultiplied RGBA as unpremultiplied RGBA

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1449] opened 2017-07-01 18:23 UTC
Testcase: [testcase](https://bugzilla.mozilla.org/attachment.cgi?id=8882833)
Screenshot:
<img width="230" alt="screen shot 2017-07-01 at 2 35 25 pm" src="https://user-images.githubusercontent.com/961291/27764573-9a0f9406-5e6a-11e7-8057-5fd4df83708e.png">
Firefox left, Servo right.

This box has a greyish fill in both servo and webrendest Gecko. It should have a yellow-whitish fill.

**Comment by mrobinson** [comment] 2017-07-12 15:09
Is this a duplicate of https://github.com/servo/webrender/issues/1354?

**Comment by mstange** [comment] 2017-07-13 22:19
Looks like it, yes.

**Comment by kvark** [comment] 2017-07-17 17:13
It appears to not be the issue about color pre-multiplication. The problem lies within blend modes we use for opacity, and the fact our cache target is cleared with black. So, having 2 opacity filters means one has to go through the cache target, and thus gets blended with black color, which screws up the result.

**Comment by kvark** [comment] 2017-07-17 17:46
@glennw I think, internally, our task API should have the (optional) clear color information. The renderer will then make sure that the task gets proper background color.

**Comment by kvark** [comment] 2017-07-17 20:30
Edit: my previous 2 comments were related to #1354, not this one.

**Closed** 2017-07-19 19:32 UTC
Labels: bug
