### ISSUE TITLE
The horizontal blur pass sometimes seems to blur in garbage from the side

### ISSUE THREAD

**Issue by mstange** [servo/webrender#1943] opened 2017-10-25 19:38 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1411693

[Testcase](https://bug1411693.bmoattachments.org/attachment.cgi?id=8922041) (created by Darkspirit)

When hovering over the element on the page, the box-shadow sometimes has extra shadows on the right edges. Here are two screenshots with and without the glitch, and with `gfx.webrender.debug.render-targets` enabled:

good frame:
<img width="1193" alt="box-shadow-good-frame" src="https://user-images.githubusercontent.com/961291/32019087-107010b4-b99a-11e7-8bab-76b8fc234cce.png">

bad frame:
<img width="1193" alt="box-shadow-bad-frame" src="https://user-images.githubusercontent.com/961291/32019096-1585206c-b99a-11e7-9624-9135edf6e153.png">

You can see that in the bad frame, the render target in the middle has a box-shadow whose right edge is a bit brighter than in the good frame. It looks like the right edge got some stuff blurred in from beyond the right edge of the rectangle that is supposed to be sampling from.

**Comment by glennw** [comment] 2017-10-26 21:51
I can reproduce this with a static box shadow that has a fractional blur radius. There must be somewhere in the code that ends up with a rounding error when a fractional blur radius is supplied. I'll work on a fix today.

**Comment by glennw** [comment] 2017-10-26 22:12
Note to self: the blur radius is correctly rounded to device pixels, but the CSS space blur radius is retained as a float. Probably related to that.

**Comment by Darkspirit** [comment] 2017-11-01 23:22
This got better with the latest webrender update. (Thank you!) Those unwanted things on the right and bottom are gone and only a white flickering is left.

Commits between the previous and latest webrender update:
https://github.com/servo/webrender/compare/4b8493d6bdc64d2d83202ac15b06b0d4b14c6e76...c0194de78ce26106a8497484dc8d159069e3a482

**Comment by Gankro** [comment] 2018-03-09 19:08
@glennw any news on this?

**Comment by glennw** [comment] 2018-03-09 20:07
@Gankro Not specifically, although the recent work I've done on box-shadows should make this easier to fix / debug. It's also possible that it may have been fixed, but I'm guessing not, from your comment here?

**Comment by Gankro** [comment] 2018-03-10 00:59
I was just following up on it since I vaguely recalled you mentioning this was going to be fixed soon. Just triaging some fuzziness that has been attributed to this.

**Comment by Darkspirit** [comment] 2018-03-10 22:09
Summary of [bug 1411693 comment 18](https://bugzilla.mozilla.org/show_bug.cgi?id=1411693#c18):
Probably #2471 made things far better. [Testcase 2](https://bugzilla.mozilla.org/attachment.cgi?id=8957846) shows the remaining problem more clearly. ([Screencast](https://bugzilla.mozilla.org/attachment.cgi?id=8957848))

**Comment by Darkspirit** [comment] 2018-06-10 11:40
[Testcase 3](https://bug1468047.bmoattachments.org/attachment.cgi?id=8984725)

**Comment by gw3583** [comment] 2019-02-01 05:00
This is resolved with the recent snapping fixes for clip masks.

**Closed by gw3583** 2019-02-01 05:00 UTC
Labels: bugzilled, type: bug
