### ISSUE TITLE
Box shadows don't render properly on mac in some cases

### ISSUE THREAD

**Issue by staktrace** [servo/webrender#2773] opened 2018-05-24 13:40 UTC
Filing for bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1452351 - the bug has a reduced test case that shows the problem on Mac. Bisection indicated the regression appeared somewhere in this range:

```
*   5cb71f0f Auto merge of #2499 - kvark:revert-fix, r=staktrace
|\
| * 9b069b7b Revert "textureSize() workaround for Angle/NV" for (somehow) causing text rendering issues on OSX.
* |   ce9c75b5 Auto merge of #2496 - jrmuizel:div, r=kvark
|\ \
| |/
|/|
| * fa1090c4 Do division and mod on unsigned integers
* |   7e459e81 Auto merge of #2497 - glennw:bi-opt, r=kvark
|\ \
| |/
|/|
| * 584459c6 Small optimization for the brush_image shader.
|/
* f3af2632 Auto merge of #2487 - glennw:bs-clip15, r=kvark
* 18cc8adb Handle minimal shadow rects with fractional offsets / sizes.
* 81f55acd Switch box-shadows to be a clip source instead of a picture.
```

So I'm guessing it's from #2487.

**Comment by Darkspirit** [comment] 2018-06-06 12:00
> Will be fixed when https://github.com/servo/webrender/pull/2799 lands in Gecko.

This can be closed.

**Comment by staktrace** [comment] 2018-06-06 12:13
I'm still seeing the problem with #2799 applied :(

**Comment by gw3583** [comment] 2018-06-06 21:18
The fix in #2799 was related to drop-shadows only, not box shadows. Specifically it was to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1458661. It looks like I incorrectly commented in https://bugzilla.mozilla.org/show_bug.cgi?id=1452351 when I meant to comment in https://bugzilla.mozilla.org/show_bug.cgi?id=1458661, sorry!

**Comment by pcwalton** [comment] 2018-09-17 22:27
Couldn't reproduce. Trying to get more info from reporter.

**Comment by gw3583** [comment] 2019-02-04 22:17
Marked fixed in related bugzilla bug.

**Closed by gw3583** 2019-02-04 22:17 UTC
Labels: bugzilled, type: bug
