### ISSUE TITLE
Strange white borders and wrong scrollbar position

### ISSUE THREAD

**Issue by stalkerg** [servo/webrender#2783] opened 2018-05-28 03:38 UTC
I tried Firefox Night with enabled WebRender on my website and saw some artifacts. 
I have:
Firefox Night 62.0a1 (2018-05-27) 
Windows 10 64bit,
Video card: nVidia 1060 with driver 397.64
I have not so popular by DPI screen - Dell UP2516 with 25'' and 2560x1440 resolution.
If I made not 100% of the scale some artifacts were going. 
Website: https://anime-pictures.net/
On the screenshot, I show firefox with webrender and normal firefox.

![screen_webrender](https://user-images.githubusercontent.com/1853716/40596069-771334f4-6273-11e8-9e15-823ef1be67e5.png)
You can see here under the right block with the chat messages the strange white line, also strange white borders in the title of the block. Also, scollbar shifted for a little. 
How it should be look:
![screenshot-2018-5-28](https://user-images.githubusercontent.com/1853716/40596093-997a3718-6273-11e8-8061-f5aa40834800.jpg)

**Comment by stalkerg** [comment] 2018-05-31 02:05
Extra screenshot with a highlight of problems:
![screen_webrender2](https://user-images.githubusercontent.com/1853716/40757224-77b9b238-64c2-11e8-9232-83c99bc09cf2.png)

**Comment by gw3583** [comment] 2018-06-04 04:53
If possible, could you raise a bugzilla bug for this? It's easier to track there when it's fixed and exactly where the issue is.

**Comment by gw3583** [comment] 2018-06-18 03:43
Did you have a chance to open a bugzilla bug? If so, we can link to it here and close this :)

**Comment by stalkerg** [comment] 2018-07-10 02:46
Done: https://bugzilla.mozilla.org/show_bug.cgi?id=1474496
Sorry for the long wait! (I was too busy)

**Comment by gw3583** [comment] 2018-07-10 02:58
Thanks!

**Comment by gw3583** [comment] 2019-02-04 22:18
Marked fixed in bugzilla.

**Closed by gw3583** 2019-02-04 22:18 UTC
Labels: type: bug
