### ISSUE TITLE
Panic in webrender::frame::Frame::flatten_item when loading http://www.firewatchgame.com/ in Servo

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#1519] opened 2017-07-25 20:11 UTC

**Comment by Gankro** [comment] 2017-07-25 20:41
This is failing:

```
        let image_template = &self.resources.image_templates.get(image_key).unwrap();
```

```
  13:        0x10861845b - webrender::frame::{{impl}}::flatten_stacking_context
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:473
  14:        0x10861a416 - webrender::frame::{{impl}}::flatten_item
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:684
  15:        0x10861b698 - webrender::frame::{{impl}}::flatten_items
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:878
  16:        0x10861845b - webrender::frame::{{impl}}::flatten_stacking_context
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:473
  17:        0x10861a416 - webrender::frame::{{impl}}::flatten_item
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:684
  18:        0x10861b698 - webrender::frame::{{impl}}::flatten_items
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:878
  19:        0x10861845b - webrender::frame::{{impl}}::flatten_stacking_context
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:473
  20:        0x10861a416 - webrender::frame::{{impl}}::flatten_item
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:684
  21:        0x10861b698 - webrender::frame::{{impl}}::flatten_items
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:878
  22:        0x10861845b - webrender::frame::{{impl}}::flatten_stacking_context
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:473
  23:        0x10861a416 - webrender::frame::{{impl}}::flatten_item
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:684
  24:        0x10861b698 - webrender::frame::{{impl}}::flatten_items
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:878
  25:        0x10861b35a - webrender::frame::{{impl}}::flatten_root
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:847
  26:        0x108617220 - webrender::frame::{{impl}}::create
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/frame.rs:353
  27:        0x108454659 - webrender::render_backend::{{impl}}::build_scene
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/render_backend.rs:503
  28:        0x108350dc7 - webrender::render_backend::{{impl}}::run::{{closure}}
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/render_backend.rs:251
  29:        0x10834bb57 - webrender::profiler::{{impl}}::profile<(),closure>
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/profiler.rs:154
  30:        0x108451816 - webrender::render_backend::{{impl}}::run
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/render_backend.rs:244
  31:        0x10836a420 - webrender::renderer::{{impl}}::new::{{closure}}
                        at /Users/ABeingessner/dev/servo/.cargo/git/checkouts/webrender-c3596abe1cf4f320/8fd6348/webrender/src/renderer.rs:1178
  32:        0x1081f80aa - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  33:        0x1082364f3 - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:364
  34:        0x10816152a - std::panic::{{impl}}::call_once<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:296
  35:        0x1082379a9 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:479
  36:        0x10a513bdc - __rust_maybe_catch_panic
                        at src/libpanic_unwind/lib.rs:98
  37:        0x108236d0c - std::panicking::try<(),std::panic::AssertUnwindSafe<closure>>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:458
  38:        0x108235655 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:361
  39:        0x1082362ce - std::thread::{{impl}}::spawn::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:363
  40:        0x1082691d3 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:651
  41:        0x10a50f93b - std::sys::imp::thread::{{impl}}::new::thread_start
                        at src/libstd/sys_common/thread.rs:21
  42:     0x7fffa983c93a - _pthread_body
  43:     0x7fffa983c886 - _pthread_start
```

**Comment by jdm** [comment] 2017-08-15 16:28
This is the same panic that we've been complaining about in Servo: https://github.com/servo/servo/issues/17857 https://github.com/servo/servo/issues/17840

**Comment by kvark** [comment] 2017-08-15 17:48
Also https://bugzilla.mozilla.org/show_bug.cgi?id=1390422

**Comment by glennw** [comment] 2017-08-15 23:04
I have been unable to reproduce locally, but I believe it should be fixed when https://github.com/servo/webrender/pull/1576 lands in WR and Servo.

**Comment by glennw** [comment] 2017-08-30 10:05
I believe this is resolved now. Please re-open if still occurring.

**Closed by glennw** 2017-08-30 10:05 UTC
