### ISSUE TITLE
assertion failed: descriptor.width > 0 && descriptor.height 

### ISSUE THREAD

**Issue by hgallagher1993** [servo/webrender#2057] opened 2017-11-17 22:46 UTC
I got this after trying to run the benchmark on http://browserbench.org/MotionMark/

<details>
 <summary>Summary</summary>

```stack backtrace:
   0:     0x55d199fe14cc - backtrace::backtrace::trace::ha2f9b48d840fa9e7
   1:     0x55d199fe1502 - backtrace::capture::Backtrace::new::hb1ab3a81fa7b7528
   2:     0x55d19994a5b0 - servo::main::{{closure}}::hc2f6bfb5060b6c45
   3:     0x55d19bc00846 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55d199d9bea1 - std::panicking::begin_panic::hd436bb006502d994
   5:     0x55d199e377a9 - webrender::texture_cache::TextureCache::update::h9db60844dbfa606b
   6:     0x55d199e32e29 - webrender::resource_cache::ResourceCache::block_until_all_resources_added::h6cf0de17cb14b76b
   7:     0x55d199dfa197 - webrender::render_backend::Document::render::h8d1253b1217bdd5d
   8:     0x55d199dfe284 - webrender::render_backend::RenderBackend::process_document::h9043f9337f695dc9
   9:     0x55d199e039d0 - webrender::render_backend::RenderBackend::run::hdce36cc1bb4c2ee5
  10:     0x55d199d9ac2b - std::sys_common::backtrace::__rust_begin_short_backtrace::h53d1098870e197e0
  11:     0x55d199d9c1c5 - std::panicking::try::do_call::h6295dbda8b2cd63c
  12:     0x55d19bc08f0e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  13:     0x55d199db6822 - <F as alloc::boxed::FnBox<A>>::call_box::ha94de7acf4814e42
  14:     0x55d19bbff55b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:23
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  15:     0x7fccacc6b6b9 - start_thread
  16:     0x7fccac3693dc - clone
  17:                0x0 - <unknown>
ERROR:servo: assertion failed: descriptor.width > 0 && descriptor.height > 0
called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }, at /checkout/src/libcore/result.rs:906)
called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 32, message: "Broken pipe" } }) (thread CanvasThread, at /checkout/src/libcore/result.rs:906)
stack backtrace:
   0:     0x55d199fe14cc - backtrace::backtrace::trace::ha2f9b48d840fa9e7
   1:     0x55d199fe1502 - backtrace::capture::Backtrace::new::hb1ab3a81fa7b7528
   2:     0x55d19994a5b0 - servo::main::{{closure}}::hc2f6bfb5060b6c45
   3:     0x55d19bc00846 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55d19bc006dc - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55d19bc005f9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55d19bc00582 - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55d19bc10de0 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55d19b0b5ded - core::result::unwrap_failed::ha7c180ed95e322b3
   9:     0x55d19b0b808a - webrender_api::api::RenderApi::set_display_list::h7829c74d3277b43e
  10:     0x55d199f2d7f0 - layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::{{closure}}::hf98894c7f6cf881a
  11:     0x55d199f36c76 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::hc47b2e61819ee6aa
  12:     0x55d199f35e90 - layout_thread::LayoutThread::tick_all_animations::h4ad92f3e6d599e3d
  13:     0x55d199f23bab - layout_thread::LayoutThread::handle_request_helper::hcbdad630b40e2e09
  14:     0x55d199f1f7c4 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::hf858e4f0326ad4b8
  15:     0x55d199e8f275 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a9d835a30848c4a
  16:     0x55d199e93425 - std::panicking::try::do_call::h84937c1a37c37720
  17:     0x55d19bc08f0e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  18:     0x55d199ec31b2 - <F as alloc::boxed::FnBox<A>>::call_box::h7a9925671362e82b
  19:     0x55d19bbff55b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:23
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  20:     0x7fccacc6b6b9 - start_thread
  21:     0x7fccac3693dc - clone
  22:                0x0 - <unknown>
ERROR:servo: called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
stack backtrace:
   0:     0x55d199fe14cc - backtrace::backtrace::trace::ha2f9b48d840fa9e7
   1:     0x55d199fe1502 - backtrace::capture::Backtrace::new::hb1ab3a81fa7b7528
   2:     0x55d19994a5b0 - servo::main::{{closure}}::hc2f6bfb5060b6c45
   3:     0x55d19bc00846 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55d19bc006dc - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55d19bc005f9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55d19bc00582 - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55d19bc10de0 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55d19b0b5ded - core::result::unwrap_failed::ha7c180ed95e322b3
   9:     0x55d19b0b7e20 - webrender_api::api::RenderApi::update_resources::h9d1e88b065050c48
  10:     0x55d199ceb0d8 - canvas::canvas_paint_thread::CanvasPaintThread::start::{{closure}}::hb8f9035b2543a1b2
  11:     0x55d199c8ac4b - std::sys_common::backtrace::__rust_begin_short_backtrace::hf59994b09215651d
  12:     0x55d199c8aceb - std::panicking::try::do_call::h8b32cbeb495b6218
  13:     0x55d19bc08f0e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  14:     0x55d199cb1b06 - <F as alloc::boxed::FnBox<A>>::call_box::h0b7483b4c75accf5
  15:     0x55d19bbff55b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:23
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  16:     0x7fccacc6b6b9 - start_thread
  17:     0x7fccac3693dc - clone
  18:                0x0 - <unknown>
ERROR:servo: called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 32, message: "Broken pipe" } })
Failed to send CloneApi message: Io(Error { repr: Os { code: 32, message: "Broken pipe" } }) (thread Constellation, at /checkout/src/libcore/result.rs:906)
stack backtrace:
   0:     0x55d199fe14cc - backtrace::backtrace::trace::ha2f9b48d840fa9e7
   1:     0x55d199fe1502 - backtrace::capture::Backtrace::new::hb1ab3a81fa7b7528
   2:     0x55d19994a5b0 - servo::main::{{closure}}::hc2f6bfb5060b6c45
   3:     0x55d19bc00846 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55d19bc006dc - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55d19bc005f9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55d19bc00582 - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55d19bc10de0 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55d19b0b5ded - core::result::unwrap_failed::ha7c180ed95e322b3
   9:     0x55d19b0b7b34 - webrender_api::api::RenderApiSender::create_api::h8dce7d9117beda34
  10:     0x55d199974949 - constellation::pipeline::UnprivilegedPipelineContent::start_all::h954b4f2c3606f6db
  11:     0x55d199a02bdc - <constellation::constellation::Constellation<Message, LTF, STF>>::new_pipeline::h6a66622859096757
  12:     0x55d1999ffe63 - <constellation::constellation::Constellation<Message, LTF, STF>>::handle_panic::hec5098c7dbd71a3d
  13:     0x55d199a0f318 - <constellation::constellation::Constellation<Message, LTF, STF>>::handle_log_entry::hc50c215dfe1f9266
  14:     0x55d199a24582 - <constellation::constellation::Constellation<Message, LTF, STF>>::handle_request_from_compositor::hcd512ee8baaa7ed6
  15:     0x55d199a09bac - <constellation::constellation::Constellation<Message, LTF, STF>>::handle_request::hf751d99b9427cfc3
  16:     0x55d1999a9801 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4d29131def094b25
  17:     0x55d1999aa555 - std::panicking::try::do_call::h8a194c6f1dde701d
  18:     0x55d19bc08f0e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  19:     0x55d1999ea6f2 - <F as alloc::boxed::FnBox<A>>::call_box::h5b6e912427c261af
  20:     0x55d19bbff55b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:23
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  21:     0x7fccacc6b6b9 - start_thread
  22:     0x7fccac3693dc - clone
  23:                0x0 - <unknown>
ERROR:servo: Failed to send CloneApi message: Io(Error { repr: Os { code: 32, message: "Broken pipe" } })
IpcSelectionResult::unwrap(): channel 1 closed (thread ResourceManager, at .cargo/registry/src/github.com-1ecc6299db9ec823/ipc-channel-0.9.0/src/ipc.rs:334)
stack backtrace:
   0:     0x55d199fe14cc - backtrace::backtrace::trace::ha2f9b48d840fa9e7
   1:     0x55d199fe1502 - backtrace::capture::Backtrace::new::hb1ab3a81fa7b7528
   2:     0x55d19994a5b0 - servo::main::{{closure}}::hc2f6bfb5060b6c45
   3:     0x55d19bc00846 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55d19bc006dc - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55d19bc005f9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55d19b12e393 - ipc_channel::ipc::IpcSelectionResult::unwrap::h4d4b3d0ac7f10ae5
   7:     0x55d199b7bae4 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcae92f5aae22222d
   8:     0x55d199b822ef - std::panicking::try::do_call::hfa5e246dfd33265c
   9:     0x55d19bc08f0e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  10:     0x55d199bb0dfe - <F as alloc::boxed::FnBox<A>>::call_box::hd94f39d06eb292ce
  11:     0x55d19bbff55b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:23
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  12:     0x7fccacc6b6b9 - start_thread
  13:     0x7fccac3693dc - clone
  14:                0x0 - <unknown>
ERROR:servo: IpcSelectionResult::unwrap(): channel 1 closed
called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(1), index: PipelineIndex(NonZero(NonZero(4))) }, at /checkout/src/libcore/result.rs:906)
internal error: entered unreachable code (thread LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }, at /checkout/src/libstd/sync/mpsc/mod.rs:916)
stack backtrace:
   0:     0x55d199fe14cc - backtrace::backtrace::trace::ha2f9b48d840fa9e7
   1:     0x55d199fe1502 - backtrace::capture::Backtrace::new::hb1ab3a81fa7b7528
   2:     0x55d19994a5b0 - servo::main::{{closure}}::hc2f6bfb5060b6c45
   3:     0x55d19bc00846 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55d19bc006dc - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55d19bc005f9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55d19bc00582 - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55d19bc10de0 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55d199f53608 - core::result::unwrap_failed::h088f710a408b94e1
   9:     0x55d199f8d186 - <layout::fragment::Fragment as layout::display_list_builder::FragmentDisplayListBuilding>::build_fragment_type_specific_display_items::he829f1f86aae765f
  10:     0x55d199f8b6f2 - <layout::fragment::Fragment as layout::display_list_builder::FragmentDisplayListBuilding>::build_display_list::hb61a242da5692638
  11:     0x55d199f928a1 - <layout::inline::InlineFlow as layout::display_list_builder::InlineFlowDisplayListBuilding>::build_display_list_for_inline::haea31cec4f37a77d
  12:     0x55d199fd5452 - layout::traversal::BuildDisplayList::traverse::hb76361ef528500fe
  13:     0x55d199fd54a2 - layout::traversal::BuildDisplayList::traverse::hb76361ef528500fe
  14:     0x55d199fd54a2 - layout::traversal::BuildDisplayList::traverse::hb76361ef528500fe
  15:     0x55d199fbd514 - layout::sequential::build_display_list_for_subtree::h2171f8fe33ba5bb6
  16:     0x55d199f2ad0a - layout_thread::LayoutThread::compute_abs_pos_and_build_display_list::{{closure}}::hf98894c7f6cf881a
  17:     0x55d199f36c76 - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::hc47b2e61819ee6aa
  18:     0x55d199f31f5d - layout_thread::LayoutThread::handle_reflow::he3049b50b4c12a5c
  19:     0x55d199f236ff - layout_thread::LayoutThread::handle_request_helper::hcbdad630b40e2e09
  20:     0x55d199f1f581 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::hf858e4f0326ad4b8
  21:     0x55d199e8f275 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a9d835a30848c4a
  22:     0x55d199e93425 - std::panicking::try::do_call::h84937c1a37c37720
  23:     0x55d19bc08f0e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  24:     0x55d199ec31b2 - <F as alloc::boxed::FnBox<A>>::call_box::h7a9925671362e82b
  25:     0x55d19bbff55b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:23
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  26:     0x7fccacc6b6b9 - start_thread
  27:     0x7fccac3693dc - clone
  28:                0x0 - <unknown>
ERROR:servo: called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 104, message: "Connection reset by peer" } })
called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 32, message: "Broken pipe" } }) (thread ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }, at /checkout/src/libcore/result.rs:906)
stack backtrace:
   0:     0x55d199fe14cc - backtrace::backtrace::trace::ha2f9b48d840fa9e7
   1:     0x55d199fe1502 - backtrace::capture::Backtrace::new::hb1ab3a81fa7b7528
   2:     0x55d19994a5b0 - servo::main::{{closure}}::hc2f6bfb5060b6c45
   3:     0x55d19bc00846 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55d19bc006dc - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:538
   5:     0x55d19bc005f9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55d19bc00582 - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55d19bc10de0 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55d19a53b47d - core::result::unwrap_failed::h02c127029616c1a1
   9:     0x55d19a2a5f0a - std::panicking::try::do_call::h3817ebf985489fb9
  10:     0x55d19bc08f0e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  11:     0x55d19aa0b67f - script::dom::bindings::codegen::Bindings::CanvasRenderingContext2DBinding::CanvasRenderingContext2DBinding::clearRect::hc2a2179c87f1760a
  12:     0x55d19b209ee4 - CallJitMethodOp
  13:     0x55d19a6eda76 - script::dom::bindings::utils::generic_call::h0b78dab22e43a31b
  14:     0x7fcca6418f6c - <unknown>
ERROR:servo: called `Result::unwrap()` on an `Err` value: Io(Error { repr: Os { code: 32, message: "Broken pipe" } })
stack backtrace:
   0:     0x55d199fe14cc - backtrace::backtrace::trace::ha2f9b48d840fa9e7
   1:     0x55d199fe1502 - backtrace::capture::Backtrace::new::hb1ab3a81fa7b7528
   2:     0x55d19994a5b0 - servo::main::{{closure}}::hc2f6bfb5060b6c45
   3:     0x55d19bc00846 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:578
   4:     0x55d199e90411 - std::panicking::begin_panic::h464e57aa3b8e40d6
   5:     0x55d199ebc09e - core::ptr::drop_in_place::hf5964937395662a0
   6:     0x55d199f29d97 - layout_thread::LayoutThread::handle_request_helper::hcbdad630b40e2e09
   7:     0x55d199f1f7c4 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::hf858e4f0326ad4b8
   8:     0x55d199e8f275 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a9d835a30848c4a
   9:     0x55d199e93425 - std::panicking::try::do_call::h84937c1a37c37720
  10:     0x55d19bc08f0e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  11:     0x55d199ec31b2 - <F as alloc::boxed::FnBox<A>>::call_box::h7a9925671362e82b
  12:     0x55d19bbff55b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:23
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  13:     0x7fccacc6b6b9 - start_thread
  14:     0x7fccac3693dc - clone
  15:                0x0 - <unknown>
ERROR:servo: internal error: entered unreachable code
thread panicked while panicking. aborting.
Stack trace for thread "LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(NonZero(NonZero(1))) }"
stack backtrace:
   0:     0x55d199fe14cc - backtrace::backtrace::trace::ha2f9b48d840fa9e7
   1:     0x55d199fe1502 - backtrace::capture::Backtrace::new::hb1ab3a81fa7b7528
   2:     0x55d199946ccb - servo::install_crash_handler::handler::ha01116bbbc766465
   3:     0x7fccac2974af - <unknown>
   4:     0x55d19bc00898 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:590
   5:     0x55d199e90411 - std::panicking::begin_panic::h464e57aa3b8e40d6
   6:     0x55d199ebc09e - core::ptr::drop_in_place::hf5964937395662a0
   7:     0x55d199f29d97 - layout_thread::LayoutThread::handle_request_helper::hcbdad630b40e2e09
   8:     0x55d199f1f7c4 - <layout_thread::LayoutThread as layout_traits::LayoutThreadFactory>::create::{{closure}}::hf858e4f0326ad4b8
   9:     0x55d199e8f275 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a9d835a30848c4a
  10:     0x55d199e93425 - std::panicking::try::do_call::h84937c1a37c37720
  11:     0x55d19bc08f0e - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
  12:     0x55d199ec31b2 - <F as alloc::boxed::FnBox<A>>::call_box::h7a9925671362e82b
  13:     0x55d19bbff55b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:772
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:23
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:90
  14:     0x7fccacc6b6b9 - start_thread
  15:     0x7fccac3693dc - clone
  16:                0x0 - <unknown>
Servo exited with return value -4
```
</details>

**Comment by glennw** [comment] 2018-01-24 01:05
I ran through the MM test suite today, and was unable to reproduce this. Has anyone seen this recently?

**Comment by hgallagher1993** [comment] 2018-01-25 09:31
I built the latest Servo in release mode yesterday and ya there was no assertion failed when I ran motion mark.

**Comment by kvark** [comment] 2018-01-25 17:10
Ok, closing then. Thanks!

**Closed by kvark** 2018-01-25 17:10 UTC
Labels: type: bug
