### ISSUE TITLE
Inset box-shadows on large elements cause rendering glitches

### ISSUE THREAD

**Issue by mstange** [servo/webrender#2135] opened 2017-11-29 20:10 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1421272

[Testcase](https://bug1421272.bmoattachments.org/attachment.cgi?id=8933009) (you may need to zoom in a bit)

On this page, WebRender renders garbage in the box-shadow area, and the text in my tabs disappears, and so does the back button.

When fixing this, please don't just apply something special for inset box-shadows that makes them require less render target space. Please also make sure that when a certain element requires too much space in the render target, we only break that particular element and keep the rest of the scene unaffected.

**Comment by Darkspirit** [comment] 2017-11-29 20:56
(Another inset box shadow regression from the same WebRender update: #2068)

**Comment by glennw** [comment] 2018-03-16 06:28
I believe this is fixed now, as a result of the box shadows being drawn as a clip source. I tested at multiple zoom levels and couldn't see a problem. @Darkspirit or @mstange are you able to confirm?

**Comment by jdm** [comment] 2018-03-16 06:48
I can't see the problem I originally reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1421272 anymore.

**Comment by glennw** [comment] 2018-04-06 04:01
Related bugzilla bug is closed, and I cannot reproduce locally with that test case.

**Closed by glennw** 2018-04-06 04:01 UTC
Labels: bugzilled, type: bug

**Comment by Darkspirit** [comment] 2018-04-06 04:29
I think the test case was broken until it crashed (not proven), and looked fine when the crash was fixed.

https://bugzilla.mozilla.org/show_bug.cgi?id=1442921#c16
The GraphicsCriticalError of the crash was introduced by #2459 as part of this WR update: https://github.com/servo/webrender/compare/8a19316a733a484bf9bafb8257e3008b1418bfe4...22b831c02479eea31821f49a0fac7dd699083557
#2487 fixed the crash of the test case.
