### ISSUE TITLE
attach_and_bind_shaders calls bind_attrib_location on names that don't exist in the shader

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#785] opened 2017-01-26 15:32 UTC
e.g.  gl::bind_attrib_location(self.id, ClipAttribute::DataIndex as gl::GLuint, "aClipDataIndex"); is called on non-clip shaders.

Sotaro is seeing shader link failures on Android caused by this.

cc: @sotaroikeda

**Comment by jrmuizel** [comment] 2017-01-26 18:59
I may have misdiagnosed this...

**Comment by kvark** [comment] 2017-01-26 19:44
This is a valid use-case in GLES 3.0:
> Hence it is allowed to bind any name to an index, including a name that is never used as an attribute in any vertex shader object. Assigned bindings for attribute variables that do not exist or are not active are ignored

I think our errors are caused by aliasing:
> Binding  more  than  one  attribute  name  to  the  same  location  is  referred  to as aliasing
,  and is not permitted in OpenGL ES Shading Language 3.00 vertex shaders.

**Comment by sotaroikeda** [comment] 2017-01-26 20:37
The following is actual error log when the problem happened.
> Adreno  : Error: Input aClipDataIndex location or component conflict with others.

**Comment by kvark** [comment] 2017-01-26 20:39
Thanks for the confirmation, @sotaroikeda !

**Comment by kvark** [comment] 2017-01-26 22:27
Actually, this is dupe of #758

**Closed by kvark** 2017-01-26 22:27 UTC
