### ISSUE TITLE
continuous insta-crashes when enabling Webrender.

### ISSUE THREAD

**Issue by Betsy25** [servo/webrender#1976] opened 2017-11-01 10:36 UTC
If this is not the correct place to file a bug, feel free to close it.
Using FF nightly with, when setting these prefs...

`gfx.webrender.enabled --> true`
`gfx.webrender.blob-images --> true`

... I get continuous insta-crashes upon (re-)starting the browser. Had to revert them from the prefs.js

All crash reports look exactly the [same](https://crash-stats.mozilla.com/report/index/bb639203-7761-47ad-8763-b7b110171031), except for the "Crash Reason", which sometimes is EXCEPTION_ACCESS_VIOLATION_READ or else EXCEPTION_ACCESS_VIOLATION_WRITE

Graphics card :  AMD Mobility Radeon HD 5000 Series (with latest released driver for it)

**Comment by jrmuizel** [comment] 2017-11-01 15:02
This crash is being tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1412848. I can't reproduce it locally, and don't have a theory about why it's crashing.

**Comment by jrmuizel** [comment] 2017-11-01 15:03
Can you try this with a fresh profile?

**Comment by Betsy25** [comment] 2017-11-01 15:24
> Can you try this with a fresh profile?

I started with Extensions disabled, and while the browser window stayed empty for a couple of seconds upon starting, it didn't crash.

**Comment by jrmuizel** [comment] 2017-11-01 15:26
Can you narrow down which extension might be related to crash?

**Comment by Betsy25** [comment] 2017-11-01 15:46
> Can you narrow down which extension might be related to crash?
It seems like it doesn't matter, as long as any extension is enabled.
Only _uBlock Origin_ enabled --> 5sec hang + crash upon start.
Only _Bitwarden - Free Password Manager_ enabled --> 5sec hang + crash upon start.

**Comment by jrmuizel** [comment] 2017-11-01 17:00
Weird. I can not reproduce the problem when I install both of those extensions

**Comment by Betsy25** [comment] 2017-11-01 17:14
Yes, there are a lot of users in the [Nightly thread](http://forums.mozillazine.org/viewtopic.php?p=14773683#p14773683) on Mozillazine forums, who uses all kind of extensions, some including those, and most of them seem to experience no crashes. One other member who also uses a HD 5000 series graphics card experiences extreme long loading times. (That probably ain't related to my crashing problem)

**Comment by jrmuizel** [comment] 2017-11-01 17:18
Do you have any special font settings that you can think of?

**Comment by Betsy25** [comment] 2017-11-01 17:35
Nope, nothing different from the default AFAIK.
[Screen 1](http://www.imagebam.com/image/89ec4e644051433)
[Screen 2](http://www.imagebam.com/image/d45968644051453)

**Comment by Betsy25** [comment] 2017-11-02 20:55
Just chiming in to post my new findings.
Switching **only** _gfx.webrender.enabled_ to _true_ does **NOT** crash the browser, but there is a 5-6sec long blank browser window upon start.

It is the _gfx.webrender.blob-images_ that is insta-crashing the browser.

**Comment by jrmuizel** [comment] 2017-11-02 21:10
@Darkspirit figured out that the crash was happening only in 32bit builds. I can reproduce it now so it should be easy to fix.

**Comment by jrmuizel** [comment] 2017-11-03 01:27
A fix to this problem has landed. It should make it into tomorrow's Nightly build.

**Comment by glennw** [comment] 2017-11-03 03:48
Closing this since it's fixed and tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1412848.

**Closed by glennw** 2017-11-03 03:48 UTC
