### ISSUE TITLE
Incorrect clipping on https://godotengine.org/download/linux

### ISSUE THREAD

**Issue by nical** [servo/webrender#2380] opened 2018-02-05 08:44 UTC
Go to https://godotengine.org/download/linux using firefox nightly with WebRender enabled, and scroll around. Notice the clipping of the blue mascot on the left.

**Comment by gmorenz** [comment] 2018-03-05 23:26
I can reliably trigger a firefox nightly crash on this page, I suspect the cause may be the same. For whatever reason the first crash report didn't get a stack trace.

Reproduction instructions: Load page, wave mouse around in bottom right corner.

1. [Crash](https://crash-stats.mozilla.com/report/index/07c188c6-e712-4edc-8287-62f780180305)
2. [Crash](https://crash-stats.mozilla.com/report/index/98387378-90f6-4f67-8d55-01c1e0180305)
3. [Crash](https://crash-stats.mozilla.com/report/index/77527dda-9187-4391-a340-400e30180305)
4. [Crash](https://crash-stats.mozilla.com/report/index/fe278937-5791-443d-9fd9-4d1110180305)

**Comment by Darkspirit** [comment] 2018-03-05 23:41
Offtopic: I can confirm that your crash was fixed by #2490.

**Comment by Darkspirit** [comment] 2018-04-04 22:56
[WR @ 3d541ccee469638603ec194da09227c991642c64](https://bugzilla.mozilla.org/show_bug.cgi?id=1449562#c5)
mozregression --repo try --launch 3b33947edef50c7f1cf9ee1d5f087067df57863e --pref gfx.webrender.all:true startup.homepage_welcome_url:"https://godotengine.org/download/linux"
bad

[WR @ 7ca4558f247ac02b9a49c0a9bf5d3972c451092f](https://bugzilla.mozilla.org/show_bug.cgi?id=1449562#c5)
mozregression --repo try --launch e9dc076b65fb82417dfe244c2516913c18f672b0 --pref gfx.webrender.all:true startup.homepage_welcome_url:"https://godotengine.org/download/linux"
good

Fix range: https://github.com/servo/webrender/compare/3d541ccee469638603ec194da09227c991642c64...7ca4558f247ac02b9a49c0a9bf5d3972c451092f

This was a dupe of #2334 (which I never mentioned, lol), which was duped to #2584.

Fixed by #2588.

**Closed** 2018-04-04 23:03 UTC
Labels: type: bug
