### ISSUE TITLE
Glitchy text-shadow when blurred.

### ISSUE THREAD

**Issue by pygy** [servo/webrender#1658] opened 2017-09-02 23:04 UTC
Hello!

```HTML
<style>
div {
  font-size: 10em;
  text-shadow: 10px 10px 10px red;
}
</style>
<div>Hello</div>
```

renders like this:

![screen shot 2017-09-03 at 00 56 55](https://user-images.githubusercontent.com/54515/29999301-4345eea8-9043-11e7-894e-67b9df728a6a.png)

[live here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHjmIE9YA+AHTQAmEAG4ACYP1Giw9YgFo4EAF4xEogIwAGGFgDck0YwAe8uIQwDaAdzVaADkY2aHTlwCcYA-WgC+-FgD07FwwfGgsQsLcABIwUFC0gZHcID4U6Ni4iAQAVghUdAxMxHip6SCYOHj41HD5NLLFpT4Auj5AA)

(Flems doesn't work in Servo, but the issue also shows up in FF57.0a with `webrendest.enabled` set to `true`, and Flems works fine there)

**Comment by pygy** [comment] 2017-09-03 15:13
The culprit is the blur param. At `0.0083333333px` the shadow looks fine, at `0.0083333334px` they start to look blocky.

**Comment by emilio** [comment] 2017-09-03 19:00
cc @Gankro

**Comment by Gankro** [comment] 2017-09-05 14:48
Confirmed, even happens in wrench. Looks like it's probably a bug in the shaders? 

wrench reftest:

```
---
root:
  items:
        -
          type: "text-shadow"
          blur-radius: 5
          bounds: [14, 18, 205, 35]
          offset: [0, 0]
          color: black
        -
          bounds: [14, 18, 205, 35]
          glyphs: [55]
          offsets: [16, 43]
          size: 18
          color: [0, 0, 0, 1.0]
          font: "VeraBd.ttf"
        -
          type: "pop-text-shadow"
```

Interestingly, making the source glyph color `[0,0,0,0]` gives correct results. Something spooky happening.

**Comment by glennw** [comment] 2017-09-05 22:05
I suspect this will be a regression from https://github.com/servo/webrender/pull/1602 - will investigate today.

**Comment by glennw** [comment] 2017-09-05 22:44
Fixed by #1658.

**Closed** 2017-09-06 19:44 UTC

**Comment by pygy** [comment] 2017-09-07 22:55
Wow, that was fast :-)

Could someone explain to me the `0.0083333333022892468px` => `0.0083333333022892469px` threshold?

**Comment by glennw** [comment] 2017-09-07 23:21
I *think* what was happening was that if the radius was considered to be 0, the code runs through a fast path where it doesn't apply the blur at all. In this fast path, the bug would not be seen (since we only need to switch from subpx glyphs to alpha masked glyphs when applying the blur filter).

**Comment by pygy** [comment] 2017-09-07 23:44
Thanks, that was my guess too, what piques my curiosity is the sub 64 bit float precision of the threshold, but if you don't know why off the top of your head, don't bother looking it up :-)

**Comment by glennw** [comment] 2017-09-07 23:49
Yea, I'm not exactly sure what causes that :)
