### ISSUE TITLE
Run reftests on Windows using ANGLE

### ISSUE THREAD

**Issue by jrmuizel** [servo/webrender#2420] opened 2018-02-14 20:30 UTC
This should let us catch any ANGLE related problem earlier

**Comment by SimonSapin** [comment] 2018-02-14 20:32
We already have a dev-dependency on ANGLE (so building should already be solved), but so far it’s only used in an ANGLE-specific shader compilation test.

**Comment by glennw** [comment] 2018-02-14 20:35
This is a duplicate of https://github.com/servo/webrender/issues/1432.

**Comment by glennw** [comment] 2018-02-14 20:35
Well, actually the other bug doesn't mention running reftests - I'll re-open this one and close the other.

**Comment by SimonSapin** [comment] 2018-02-14 20:39
https://github.com/servo/webrender/issues/2006#issuecomment-342622794
> Wrench uses glutin for initialization, and that one checks for libEGL as of servo/glutin#112 . All you need is to drop Angle's `libEGL.dll` in the folder with wrench executable.

**Comment by SimonSapin** [comment] 2018-02-23 16:45
> We already have a dev-dependency on ANGLE (so building should already be solved)

I was probably a bit too optimistic there. The crate at https://github.com/servo/angle self-describes as "GLSL parsing and validation library based on ANGLE"  so possibly it doesn’t compile all of the relevant code. It also produces a static library, whereas Glutin uses (effectively) `LoadLibraryA("libEGL.dll")`.

**Comment by SimonSapin** [comment] 2018-03-04 17:42
https://crates.io/crates/mozangle + https://github.com/tomaka/glutin/pull/998 should enable running Wrench with ANGLE on Windows in non-headless mode.

However headless mode still uses OSMesa, and our Windows CI doesn’t run reftests at all at the moment. @jrmuizel Did you mean this issue to be about running reftests on CI?

**Comment by jrmuizel** [comment] 2018-03-06 16:30
Yes, I'd like to have the reftests running in CI on ANGLE

**Comment by SimonSapin** [comment] 2018-03-15 18:07
https://github.com/servo/webrender/pull/2529 adds `wrench --angle`. 7 reftests fail, even with some fuzzy matching:

```
        reftests\border\border-suite-2.yaml == reftests\border\border-suite-2.png
        reftests\border\dotted-corner-small-radius.yaml == reftests\border\dotted-corner-small-radius.png
        reftests\boxshadow\inset-subpx.yaml == reftests\boxshadow\inset-subpx.png
        reftests\image\downscale.yaml == reftests\image\downscale.png
        reftests\transforms\image-rotated-clip.yaml == reftests\transforms\image-rotated-clip.png
        reftests\transforms\nested-rotate-x.yaml == reftests\transforms\nested-rotate-x.png
        reftests\transforms\nested-preserve-3d.yaml == reftests\transforms\nested-preserve-3d.png
```

Full output of `cargo run --release -- --angle reftest --fuzzy 10`: https://gist.github.com/anonymous/fc947365525cd6066b3eb77d10084cdd

**Comment by glennw** [comment] 2018-03-28 21:06
I opened up the reftest log, and none of the failing tests look *completely wrong*. Most of them are a lot of subpixel differences compared to the PNG reference images on Linux, which is somewhat expected.

If we disable those tests on Windows *temporarily*, by adding ```platform(max,linux)``` to the reftest.list file for those tests, we should be able to enable windows reftests in CI.

Does that sound correct to you @SimonSapin ?

**Comment by glennw** [comment] 2018-03-28 21:06
Long term, we need to either use PNG images less often, or support generating them per-platform (probably a combination of both).

**Comment by glennw** [comment] 2018-05-03 21:58
This happened. We still need to enable some of the PNG reference tests on Windows, but we have ~80% coverage.

**Closed by glennw** 2018-05-03 21:58 UTC
Labels: area: infrastructure, difficulty: easy, type: enhancement
