### ISSUE TITLE
Text with multiple runs triggers assert

### ISSUE THREAD

**Issue by excaliburHisSheath** [servo/webrender#752] opened 2017-01-19 16:28 UTC
I'm running into an issue where trying rendering text with more than 8 glyphs causes [this debug assert][debug assert] to trigger. I've traced the underlying issue to the changes introduced in #729 by @glennw, though I can't tell if those changes are actually the source of the bug. What seems to be happening is that text primitives with more than 8 glyphs get broken up into multiple runs. These runs don't have their own clip info so their render tasks all get keyed with the stacking context, but they all have different sizes which causes them to trigger the assert.

If I'm understanding the situation correctly, the bug goes as follows:

- The user pushes some text with more than 8 glyphs.
- Later, when the frame is created, `FrameBuilder::add_text()` is called for that text. `add_text()` is hardcoded to break text up into runs of at most 8 glyphs, so the user's text is broken into 2 or more runs, each of which is passed to `FrameBuilder::add_primitive()`.
- `add_primitive()` creates a `PrimitiveRunCmd::PrimitiveRun` for each glyph run.
- Later, `FrameBuilder::cull_layers()` processes the primitive run commands. If the run command's primitive metadata (created when the primitive was added to the frame builder) has no clip info (which the glyph runs don't seem to) their render task is keyed with the stacking context index. Each run in the original text is therefore given the same key because all runs in the same text will have the same stacking context.
- Later, `RenderPass::build()` will try to reuse a previous dynamic allocation, but will fail the assert. This is because all the 8 glyph runs in the user's text retrieve the same cached dynamic allocation, but each render pass has a different size.

I'd like to submit a PR to fix this, but my inexperience with webrender makes it hard for me to tell what the correct solution is. Does anyone know more about what's going on or what the cause of the bug might be?

[debug assert]: https://github.com/servo/webrender/blob/69f5804414865a0143def46564b2aadee2ad08e8/webrender/src/tiling.rs#L1036

**Comment by excaliburHisSheath** [comment] 2017-01-19 16:50
Thinking about it (and I could be totally off-base here), the issue is likely either in the code introduced in #729 or in the logic for reusing primitives in `RenderPass::build()`. #729 introduces logic that primitives that don't have their own clip (as is the case with the text runs) can share a clip mask, but the clip masks that are reused in `RenderPass::build()` are the bounding box of that text run, which means it's specific to that text run and shouldn't be shared. The two things seem to be in conflict, though I don't know which one is "wrong".

**Comment by glennw** [comment] 2017-01-19 16:57
Interesting! I *think* the problem is actually that the debug_assert is not valid in this situation. Is there a way I can reproduce this to confirm what is going on?

**Comment by excaliburHisSheath** [comment] 2017-01-19 17:08
It's not a super minimal example, but https://github.com/excaliburHisSheath/text-edit is what I'm working with currently. The `text-assert-repro` branch has the repro all setup, you can `cargo run` and it should repro.

**Comment by excaliburHisSheath** [comment] 2017-01-19 17:30
So here's what happens when I comment out the `debug_assert!()`:

![webrender_panic_commented](https://cloud.githubusercontent.com/assets/1900829/22117658/6c3ba278-de3a-11e6-93ec-bbf11ca49ee3.PNG)
 
The red box shows the clipping mask (?_? I think) used by the first text run, the green box shows the one that *should* be used by the second run. But, as per #729, they share a clipping mask, so they both use the red box and the second run gets clipped (except for it where it overlaps the first run, as is slightly visible in the screenshot above).

**Comment by glennw** [comment] 2017-01-19 18:16
Thanks for the repro - I'll try to take a look today.

**Comment by glennw** [comment] 2017-01-19 18:25
When I ```cargo run``` that branch, I don't see any assert. The text is very small and a different font from above, so perhaps a difference due to my system fonts?

**Comment by excaliburHisSheath** [comment] 2017-01-19 18:48
Ah, sorry about that! I commit the latest version of the webrender submodule on that branch, run `git pull` and then `git submodule update --recursive --remote`, and that should get you up to date.

The version that runs won't be using the same font as the screenshot, though. I had to do some debugging to visualize the text bounds (i.e. `println!()` to find out the bounds webrender was using) in that screenshot, so I don't have code that reproduces it. And I used a different font because it demonstrates better that the second run is getting clipped based on the first run's mask.

**Comment by excaliburHisSheath** [comment] 2017-01-19 19:05
Actually, I think I can setup the example to reproduce the screenshot. I've just pushed an updated to the `text-assert-repro` branch, pull that down and give it a try. It should still assert by default, but if you comment out the `debug_assert!()` in webrender it should reproduce the screenshot above.

**Comment by glennw** [comment] 2017-01-19 20:10
Fixed in https://github.com/servo/webrender/pull/755.

**Comment by excaliburHisSheath** [comment] 2017-01-19 20:30
:D Thanks! I've confirmed that your change resolves the crash.

**Closed** 2017-01-20 00:51 UTC
